services:
  frontend:
    depends_on:
      - backend
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - medias:/usr/share/nginx/html/medias

  backend:
    restart: on-failure:3
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-backend
    environment:
      - PG_USER=test
      - PG_PASSWORD=test
      - PG_DATABASE=dev
      - PG_HOST=db
    volumes:
      - medias:/medias
    
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=dev

volumes:
  medias: